Remove dependency on log.py from openstack/common
Importing oslo.vmware to another OpenStack project gives the
ArgsAlreadyParsedError: arguments already parsed: cannot register CLI
option exception.
This happens because openstack/common/log.py registers CLI options
after the project using oslo.vmware parses its configuration.

This patch addresses this issue by removing any dependency on
log.py, using logging from the standard python library instead.

Change-Id: Id2bddb8a7efc2a53399e2a2278dba4605da083d8
Closes-Bug: #1284837